ARXIVNG-1329 Autogenerate pretty API documentation from OpenAPI and JSON Schema documents
cul-it/arxiv-api-gateway pull request #1
Opened 2018-11-07 23:15 UTC by erickpeirson

First pass. Mostly looking for feedback on design, overall presentation. Uses https://github.com/cul-it/arxiv-docs + Jinja2 macros. See README for how to run.

![image](https://user-images.githubusercontent.com/3451594/48167174-e5ad4d80-e2b8-11e8-9130-d0e3162f2467.png)

![image](https://user-images.githubusercontent.com/3451594/48167214-08d7fd00-e2b9-11e8-9310-888db16e69ca.png)

Pardon the inverted branches....

2018-11-07 23:16 UTC, erickpeirson commented
@mhl10 Only if you have time, lots going on

2018-11-08 01:29 UTC, erickpeirson commented
@eawoods Looking for any and all guidance on design, presentation. I feel like the look is going in a couple of different directions. There's also probably a lot that could be improved by using collapsible elements or tabs, but I wanted to start with everything-on-the-table before overthinking the interactive bits.

2018-11-09 20:19 UTC, eawoods requested changes
Some relatively minor things, mostly accessibility related.
A question: why are api/api/base.html and api/api/openapi.html required such that they duplicate content from api/templates/api/*? Just curious, fine if it's a temporary structure to get this off the ground.
To answer the question "what would be the biggest blockers for getting this out into the wild?":
- Needs a table of contents in a sidebar that's sticky.
- Needs some structural help, some of which may be inherent in the docs repo (no h1, container div repeats).
- Would strongly consider a tabular format for properties within a response. Needs design.
- Tags need a little attention to be consistent and usable.

I don't think these will take a huge amount of time to accomplish, but if we're publishing documentation then we really need to at least take a first stab at readability and scannability. I have some "API documentation guidelines" docs for reference, happy to share links as needed.

2018-11-09 20:19 UTC, eawoods commented on .gitignore
> +<<<<<<< HEAD
Maybe a leftover merge comment?

2018-11-09 20:19 UTC, eawoods commented on api/api/base.html
> +<!-- Liz is going to give you a really hard time about this, Erick... -->
The only thing I'm going to give you a hard time about atm is that this style block doesn't render at all in my build - weird because all the other head items do. I couldn't figure out why.

2018-11-09 20:19 UTC, eawoods commented on api/api/base.html
> +}
Also caution on the overuse of !important. Probably means a greater specificity is required in this case: .content ul.unstyled will do the override without the !

2018-11-09 20:19 UTC, eawoods commented on api/api/openapi.html
> +  <p class="has-text-weight-light">{{ render_markdown(schema.description) }}</p>
Pretty sure that `has-text-weight-light` doesn't do anything in our current config because we don't have the 300 weight of Open Sans loaded. This may cause undesired effects when OS is not available or if we ever decide to load in that font weight for some reason.
Also note that light font weights + small font sizes are probably out of spec for accessibility. (Recommended: drop this style)

2018-11-09 20:19 UTC, eawoods commented on api/api/openapi.html
> +        <h6 class="title is-6" id="{{ method_schema.operationId }}_requestBody_{{ response_key }}_{{ content_type }}">
A11y rules: this element should use `<h5>` to be correctly cascading headings, unless I'm not reading the inheritance correctly. If it doesn't display nicely, use text styles for override or get the designer to fix it. :)

2018-11-09 20:19 UTC, eawoods commented on api/static/css/docs.css
> +.hidden-label {
`.hidden-label` is in arxiv-base, shouldn't have to declare it here (and the inline page styles belong here)

2018-11-09 20:19 UTC, eawoods commented on api/templates/api/openapi.html
> +      <span class="tag is-warning">required</span>
very nice, looks great on the page

2018-12-19 00:05 UTC, erickpeirson commented
Closing this in favor of a ready-made solution. https://github.com/swagger-api/swagger-ui

2018-12-19 00:05 UTC, closed without merging